# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"
    driver: "gd"
    filter_sets:
        cache: ~

        # name our filter set "my_thumb_filter"
        my_card_thumb:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [350, 200]

                    # crop the input image, if required
                    mode: outbound

        rent_thumb:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [290, 342]

                    # crop the input image, if required
                    mode: outbound

        my_property_detail_thumb:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [800, 400]

                    # crop the input image, if required
                    mode: outbound
        my_home_card:
            filters:
                thumbnail:
                    size: [385, 219]
                    mode: outbound
                    
        my_galerie_image:
            filters:
                thumbnail:
                    size: [285, 213]
                    mode: outbound

        admin_property_thumb:
            filters:
                thumbnail:
                    size: [120, 85]
                    mode: outbound