# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"
    driver: "gd"
    filter_sets:
        cache: ~

        # name our filter set "my_thumb_filter"
        my_card_thumb:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [304, 203]

                    # crop the input image, if required
                    mode: outbound

        home_feature:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [416, 277]

                    # crop the input image, if required
                    mode: outbound

        detail_thumb:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [605, 454]

                    # crop the input image, if required
                    mode: outbound
        my_home_card:
            filters:
                thumbnail:
                    size: [385, 219]
                    mode: outbound
                    
        galerie_image:
            filters:
                thumbnail:
                    size: [316, 267]
                    mode: outbound

        admin_property_thumb:
            filters:
                thumbnail:
                    size: [120, 85]
                    mode: outbound
        admin_property_image:
            filters:
                thumbnail:
                    size: [60, 60]
                    mode: outbound