vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /uploads/images/property
            upload_destination: '%kernel.project_dir%/public/uploads/images/property'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        user_avatar:
            uri_prefix: /uploads/images/user/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/images/user/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
